name: Push Images
on:
  push:
    tags:
      - '*'
jobs:
  images:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
      - name: Build Go code for amd64
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o app-tool-amd64 main.go
      - name: Build Go code for arm64
        run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o app-tool-arm64 main.go
      - name: Debug docker
        run: echo ${{ secrets.DOCKER_USERNAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zichenkkkk/app-tool:${{ github.ref_name }}